---
- hosts: prod
  become: yes
  name: Installing nginx on slave1
  tasks:
  - name: Install nginx
    apt: name=nginx state=latest
    notify:
     - restart nginx
  - name: Insert Index Page
    template:
      src: index.html
      dest: /var/www/html/index.html
  - name: Enable Nginx during boot
    service: name=nginx state=started
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
