---
- hosts: prod
  gather_facts: yes
  become_user: root
  tasks:
  - name: Install Nginx
    apt: name=nginx state=present
    notify:
    - restart nginx
  - name: Enable Nginx during boot
    service: name=nginx state=started
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
